
tasks:
  - name: Installation Task
    init: > 
      bb install &&
      pip install -r requirements.txt && # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
      gp sync-done bb
    command: python test.py

  - name: script
    init: gp sync-await bb  # wait for bb to finish
    command:  python test.py
    
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

vscode:
  extensions:
    - ms-toolsai.jupyterdocs/introduction/getting-started/quickstart
